spring.application.name=EddiesBudgetingApp
#Remove when you start using Postgres! 7-9-25
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#Remove when you start using Docker! 7-9-25
spring.docker.compose.enabled=false

#Remove when you set up proper security. 7-9-25
spring.security.enabled=false
